# Builds the aeon environment; lints formatting and smells via ruff; checks type annotations via pyright;
# tests via pytest; reports test coverage via pytest-cov and codecov.

name: swc-aeon
on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]
  workflow_dispatch: # allows running manually from GitHub Actions

jobs:
  build: # build package and run codebase checks and tests using pyproject.toml
    strategy:
      fail-fast: false
      matrix:
        # Test all supported Python versions on Linux
        platform:
          - name: Linux
            os: ubuntu-latest
        python-version: ["3.11", "3.12", "3.13"]
        # Test latest supported Python version on Windows and macOS
        include:
          - platform:
              name: Linux
              os: ubuntu-latest
            python-version: "3.13"
            codecov: --cov-report=xml
            collect-packages: true
          - platform:
              name: Windows
              os: windows-latest
            python-version: "3.13"
          - platform:
              name: macOS
              os: macos-latest
            python-version: "3.13"
    name: ${{ matrix.platform.name }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform.os }}
    steps:
      # -------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v5

      # -------------------------------------------------------- Set up tools
      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      # -------------------------------------------------------- Configure build
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # -------------------------------------------------------- Build
      - name: ruff
        run: uv run ruff check .

      - name: pyright
        run: uv run pyright --level error --project ./pyproject.toml .

      - name: Build
        id: build
        run: uv build

      # -------------------------------------------------------- Test
      - name: Run tests
        run: uv run pytest tests/ --cov-report term ${{ matrix.codecov }}

      # -------------------------------------------------------- Coverage report
      - name: Upload test coverage report to codecov
        if: ${{ matrix.codecov }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      # -------------------------------------------------------- Collect artifacts
      - name: Collect Python packages
        uses: actions/upload-artifact@v4
        if: matrix.collect-packages && steps.build.outcome == 'success' && always()
        with:
          name: Packages
          if-no-files-found: error
          path: dist/

      # -------------------------------------------------------- Upload release assets
      - name: Upload release assets
        if: github.event_name == 'release'
        run: gh release upload --repo ${{ github.repository }} ${{ github.event.release.tag_name }} dist/* --clobber
        env:
          GH_TOKEN: ${{ github.token }}

  publish-pypi:
    name: Publish packages to PyPI
    runs-on: ubuntu-latest
    environment: public-release
    needs: build
    permissions:
      # Needed to attach files to releases
      contents: write
    if: github.event_name == 'release'
    steps:
      # -------------------------------------------------------- Set up tools
      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: false

      # -------------------------------------------------------- Download built packages
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist/

      # -------------------------------------------------------- Push to PyPI
      - name: Push to PyPI
        run: uv publish dist/* --token ${{ secrets.PYPI_API_TOKEN }}
